name: Validate Pull Request

on:
  pull_request:
    branches:
      - master
    paths:
      - 'force-app/**'
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate on PRD
        uses: jawills/sf-deploy@v1.0
        with:
          SFDX_AUTH_URL: ${{ secrets.AUTH_URL_PRD }}
          DRY_RUN: true
